
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: May 20 2025 10:54:47 IST (May 20 2025 05:24:47 UTC)

// Verification Directory fv/simple_8bit_cpu 

module control_unit(instr, alu_op, reg_write_en, dest_reg, src_reg,
     immediate_val, load_acc, pc_write_en, pc_sel);
  input [15:0] instr;
  output [2:0] alu_op, dest_reg, src_reg;
  output reg_write_en, load_acc, pc_write_en;
  output [7:0] immediate_val;
  output [1:0] pc_sel;
  wire [15:0] instr;
  wire [2:0] alu_op, dest_reg, src_reg;
  wire reg_write_en, load_acc, pc_write_en;
  wire [7:0] immediate_val;
  wire [1:0] pc_sel;
  wire n_1, n_2, n_3;
  NAND2XL g89__8780(.A (n_3), .B (n_2), .Y (load_acc));
  OAI32X1 g90__4296(.A0 (instr[15]), .A1 (instr[12]), .A2 (n_1), .B0
       (instr[13]), .B1 (n_2), .Y (reg_write_en));
  NOR2XL g91__3772(.A (n_1), .B (n_2), .Y (alu_op[1]));
  CLKINVX1 g92(.A (n_3), .Y (alu_op[2]));
  NAND3X1 g93__1474(.A (instr[15]), .B (instr[12]), .C (instr[13]), .Y
       (n_3));
  NAND2BX1 g94__4547(.AN (instr[15]), .B (instr[12]), .Y (n_2));
  INVX1 g95(.A (instr[13]), .Y (n_1));
endmodule

module instruction_memory(clk, addr, instruction);
  input clk;
  input [3:0] addr;
  output [15:0] instruction;
  wire clk;
  wire [3:0] addr;
  wire [15:0] instruction;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10;
  DFFQX1 \instruction_reg[9] (.CK (clk), .D (n_1), .Q
       (instruction[13]));
  DFFQX1 \instruction_reg[12] (.CK (clk), .D (n_7), .Q
       (instruction[12]));
  DFFQX1 \instruction_reg[0] (.CK (clk), .D (n_9), .Q (instruction[0]));
  DFFQX1 \instruction_reg[3] (.CK (clk), .D (n_8), .Q (instruction[3]));
  DFFQX1 \instruction_reg[15] (.CK (clk), .D (n_5), .Q
       (instruction[15]));
  DFFQX1 \instruction_reg[10] (.CK (clk), .D (n_0), .Q
       (instruction[11]));
  DFFQX1 \instruction_reg[1] (.CK (clk), .D (n_6), .Q (instruction[1]));
  OAI21X1 g186__9682(.A0 (n_3), .A1 (n_4), .B0 (addr[0]), .Y (n_10));
  NOR2BX1 g187__2683(.AN (n_6), .B (addr[1]), .Y (n_9));
  AND2XL g188__1309(.A (addr[1]), .B (n_6), .Y (n_8));
  AO21X1 g189__6877(.A0 (addr[1]), .A1 (n_4), .B0 (n_6), .Y (n_7));
  NOR2BX1 g190__2900(.AN (n_4), .B (addr[0]), .Y (n_6));
  AND3XL g192__2391(.A (addr[0]), .B (addr[1]), .C (n_4), .Y (n_5));
  NOR2XL g194__7675(.A (addr[3]), .B (addr[2]), .Y (n_4));
  NOR2XL g195__7118(.A (addr[3]), .B (addr[1]), .Y (n_3));
  NAND2BX1 g2__8757(.AN (n_0), .B (n_10), .Y (n_1));
  NOR4BBX1 g197__1786(.AN (addr[1]), .BN (addr[2]), .C (addr[3]), .D
       (addr[0]), .Y (n_0));
endmodule

module instruction_register(clk, load_ir, instr_in, instr_out);
  input clk, load_ir;
  input [15:0] instr_in;
  output [15:0] instr_out;
  wire clk, load_ir;
  wire [15:0] instr_in;
  wire [15:0] instr_out;
  DFFQX1 \instr_out_reg[15] (.CK (clk), .D (instr_in[15]), .Q
       (instr_out[15]));
  DFFQX1 \instr_out_reg[12] (.CK (clk), .D (instr_in[12]), .Q
       (instr_out[12]));
  DFFQX1 \instr_out_reg[0] (.CK (clk), .D (instr_in[0]), .Q
       (instr_out[0]));
  DFFQXL \instr_out_reg[3] (.CK (clk), .D (instr_in[3]), .Q
       (instr_out[3]));
  DFFQX1 \instr_out_reg[9] (.CK (clk), .D (instr_in[9]), .Q
       (instr_out[13]));
  DFFQX1 \instr_out_reg[10] (.CK (clk), .D (instr_in[10]), .Q
       (instr_out[11]));
  DFFQX1 \instr_out_reg[1] (.CK (clk), .D (instr_in[1]), .Q
       (instr_out[1]));
endmodule

module program_control_unit(clk, reset, pc_write_enable, pc_sel,
     branch_addr, isr_addr, PC);
  input clk, reset, pc_write_enable;
  input [1:0] pc_sel;
  input [7:0] branch_addr, isr_addr;
  output [7:0] PC;
  wire clk, reset, pc_write_enable;
  wire [1:0] pc_sel;
  wire [7:0] branch_addr, isr_addr;
  wire [7:0] PC;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  SDFFRHQX1 \PC_reg[3] (.RN (n_1), .CK (clk), .D (n_2), .SI (PC[3]),
       .SE (n_5), .Q (PC[3]));
  DFFRHQX1 \PC_reg[2] (.RN (n_1), .CK (clk), .D (n_6), .Q (PC[2]));
  OA21XL g197__5953(.A0 (PC[2]), .A1 (n_3), .B0 (n_5), .Y (n_6));
  DFFRHQX1 \PC_reg[1] (.RN (n_1), .CK (clk), .D (n_4), .Q (PC[1]));
  NAND2XL g199__5703(.A (PC[2]), .B (n_3), .Y (n_5));
  AOI2BB1X1 g200__7114(.A0N (PC[0]), .A1N (PC[1]), .B0 (n_3), .Y (n_4));
  AND2X1 g202__5266(.A (PC[1]), .B (PC[0]), .Y (n_3));
  INVX1 g204(.A (PC[3]), .Y (n_2));
  INVXL g205(.A (reset), .Y (n_1));
  DFFRX1 \PC_reg[0] (.RN (n_1), .CK (clk), .D (n_0), .Q (PC[0]), .QN
       (n_0));
endmodule

module simple_8bit_cpu(clk, reset, acc_port, reg_port);
  input clk, reset;
  output [7:0] acc_port, reg_port;
  wire clk, reset;
  wire [7:0] acc_port, reg_port;
  wire [15:0] ir_out;
  wire [2:0] alu_op;
  wire [7:0] pc;
  wire [15:0] instr;
  wire [7:0] branch_addr;
  wire [7:0] immediate_val;
  wire [7:0] \RF_reg_array[0] ;
  wire [7:0] \RF_reg_array[1] ;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED_HIER_Z,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z4;
  wire UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10,
       UNCONNECTED_HIER_Z11, UNCONNECTED_HIER_Z12;
  wire UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z19, UNCONNECTED_HIER_Z20;
  wire UNCONNECTED_HIER_Z21, UNCONNECTED_HIER_Z22,
       UNCONNECTED_HIER_Z23, UNCONNECTED_HIER_Z24,
       UNCONNECTED_HIER_Z25, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z28;
  wire UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z30,
       UNCONNECTED_HIER_Z31, UNCONNECTED_HIER_Z32,
       UNCONNECTED_HIER_Z33, UNCONNECTED_HIER_Z34,
       UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z36;
  wire UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z38,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z40, load_acc, n_0, n_1,
       n_2;
  wire n_3, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, reg_write_en;
  assign reg_port[2] = reg_port[7];
  assign reg_port[4] = reg_port[7];
  assign reg_port[5] = reg_port[7];
  assign reg_port[6] = reg_port[7];
  assign acc_port[2] = acc_port[7];
  assign acc_port[4] = acc_port[7];
  assign acc_port[5] = acc_port[7];
  assign acc_port[6] = acc_port[7];
  control_unit CU(.instr ({ir_out[15], UNCONNECTED_HIER_Z11, ir_out[9],
       ir_out[12], UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z}), .alu_op ({alu_op[2:1], UNCONNECTED}),
       .reg_write_en (reg_write_en), .dest_reg ({UNCONNECTED2,
       UNCONNECTED1, UNCONNECTED0}), .src_reg ({UNCONNECTED5,
       UNCONNECTED4, UNCONNECTED3}), .immediate_val ({UNCONNECTED13,
       UNCONNECTED12, UNCONNECTED11, UNCONNECTED10, UNCONNECTED9,
       UNCONNECTED8, UNCONNECTED7, UNCONNECTED6}), .load_acc
       (load_acc), .pc_write_en (UNCONNECTED14), .pc_sel
       ({UNCONNECTED16, UNCONNECTED15}));
  instruction_memory IM(.clk (clk), .addr (pc[3:0]), .instruction
       ({instr[15], UNCONNECTED24, instr[13:11], UNCONNECTED23,
       UNCONNECTED22, instr[8], UNCONNECTED21, UNCONNECTED20,
       UNCONNECTED19, UNCONNECTED18, instr[3], UNCONNECTED17,
       instr[1:0]}));
  instruction_register IR(.clk (clk), .load_ir (UNCONNECTED_HIER_Z12),
       .instr_in ({instr[15], UNCONNECTED_HIER_Z21,
       UNCONNECTED_HIER_Z20, instr[12], UNCONNECTED_HIER_Z19,
       instr[11], instr[13], UNCONNECTED_HIER_Z18,
       UNCONNECTED_HIER_Z17, UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z14, instr[3],
       UNCONNECTED_HIER_Z13, instr[1:0]}), .instr_out ({ir_out[15],
       UNCONNECTED32, ir_out[9], ir_out[12:11], UNCONNECTED31,
       UNCONNECTED30, ir_out[8], UNCONNECTED29, UNCONNECTED28,
       UNCONNECTED27, UNCONNECTED26, branch_addr[3], UNCONNECTED25,
       immediate_val[1:0]}));
  program_control_unit PCU(.clk (clk), .reset (reset), .pc_write_enable
       (UNCONNECTED_HIER_Z22), .pc_sel ({UNCONNECTED_HIER_Z24,
       UNCONNECTED_HIER_Z23}), .branch_addr ({UNCONNECTED_HIER_Z32,
       UNCONNECTED_HIER_Z31, UNCONNECTED_HIER_Z30,
       UNCONNECTED_HIER_Z29, UNCONNECTED_HIER_Z28,
       UNCONNECTED_HIER_Z27, UNCONNECTED_HIER_Z26,
       UNCONNECTED_HIER_Z25}), .isr_addr ({UNCONNECTED_HIER_Z40,
       UNCONNECTED_HIER_Z39, UNCONNECTED_HIER_Z38,
       UNCONNECTED_HIER_Z37, UNCONNECTED_HIER_Z36,
       UNCONNECTED_HIER_Z35, UNCONNECTED_HIER_Z34,
       UNCONNECTED_HIER_Z33}), .PC (pc));
  DFFQX1 \ALU_acc_out_reg[0] (.CK (clk), .D (n_33), .Q (acc_port[0]));
  DFFQX1 \ALU_acc_out_reg[3] (.CK (clk), .D (n_32), .Q (acc_port[3]));
  DFFQX1 \ALU_acc_out_reg[1] (.CK (clk), .D (n_29), .Q (acc_port[1]));
  NAND2XL g1336__2250(.A (n_31), .B (n_26), .Y (n_33));
  DFFQX1 \ALU_acc_out_reg[2] (.CK (clk), .D (n_27), .Q (acc_port[7]));
  INVXL g1338(.A (n_30), .Y (n_32));
  OAI21X1 g1339__6083(.A0 (n_17), .A1 (n_25), .B0 (immediate_val[0]),
       .Y (n_31));
  AOI222XL g1340__2703(.A0 (branch_addr[3]), .A1 (n_17), .B0
       (acc_port[3]), .B1 (n_16), .C0 (n_22), .C1 (n_9), .Y (n_30));
  INVXL g1341(.A (n_28), .Y (n_29));
  AOI222XL g1342__5795(.A0 (immediate_val[1]), .A1 (n_17), .B0
       (acc_port[1]), .B1 (n_16), .C0 (n_21), .C1 (n_11), .Y (n_28));
  AO22XL g1343__7344(.A0 (n_10), .A1 (n_23), .B0 (acc_port[7]), .B1
       (n_16), .Y (n_27));
  AOI32X1 g1344__1840(.A0 (n_2), .A1 (\RF_reg_array[0] [0]), .A2
       (n_24), .B0 (acc_port[0]), .B1 (n_16), .Y (n_26));
  SDFFQX1 \RF_reg_array_reg[7][2] (.CK (clk), .D (acc_port[7]), .SI
       (reg_port[7]), .SE (n_12), .Q (reg_port[7]));
  SDFFQX1 \RF_reg_array_reg[7][3] (.CK (clk), .D (acc_port[3]), .SI
       (reg_port[3]), .SE (n_12), .Q (reg_port[3]));
  SDFFQX1 \RF_reg_array_reg[0][0] (.CK (clk), .D (acc_port[0]), .SI
       (\RF_reg_array[0] [0]), .SE (n_13), .Q (\RF_reg_array[0] [0]));
  SDFFQX1 \RF_reg_array_reg[0][1] (.CK (clk), .D (acc_port[1]), .SI
       (\RF_reg_array[0] [1]), .SE (n_13), .Q (\RF_reg_array[0] [1]));
  SDFFQX1 \RF_reg_array_reg[0][2] (.CK (clk), .D (acc_port[7]), .SI
       (\RF_reg_array[0] [2]), .SE (n_13), .Q (\RF_reg_array[0] [2]));
  SDFFQX1 \RF_reg_array_reg[0][3] (.CK (clk), .D (acc_port[3]), .SI
       (\RF_reg_array[0] [3]), .SE (n_13), .Q (\RF_reg_array[0] [3]));
  SDFFQX1 \RF_reg_array_reg[1][0] (.CK (clk), .D (acc_port[0]), .SI
       (\RF_reg_array[1] [0]), .SE (n_14), .Q (\RF_reg_array[1] [0]));
  SDFFQX1 \RF_reg_array_reg[1][1] (.CK (clk), .D (acc_port[1]), .SI
       (\RF_reg_array[1] [1]), .SE (n_14), .Q (\RF_reg_array[1] [1]));
  SDFFQX1 \RF_reg_array_reg[1][2] (.CK (clk), .D (acc_port[7]), .SI
       (\RF_reg_array[1] [2]), .SE (n_14), .Q (\RF_reg_array[1] [2]));
  SDFFQX1 \RF_reg_array_reg[1][3] (.CK (clk), .D (acc_port[3]), .SI
       (\RF_reg_array[1] [3]), .SE (n_14), .Q (\RF_reg_array[1] [3]));
  SDFFQX1 \RF_reg_array_reg[7][0] (.CK (clk), .D (acc_port[0]), .SI
       (reg_port[0]), .SE (n_12), .Q (reg_port[0]));
  SDFFQX1 \RF_reg_array_reg[7][1] (.CK (clk), .D (acc_port[1]), .SI
       (reg_port[1]), .SE (n_12), .Q (reg_port[1]));
  NOR2BX1 g1357__5019(.AN (\RF_reg_array[1] [0]), .B (n_19), .Y (n_25));
  OAI21X1 g1358__1857(.A0 (n_3), .A1 (n_15), .B0 (n_20), .Y (n_24));
  OAI21X1 g1359__9906(.A0 (n_6), .A1 (n_15), .B0 (n_20), .Y (n_23));
  OAI21X1 g1360__8780(.A0 (n_0), .A1 (n_15), .B0 (n_20), .Y (n_22));
  OAI21X1 g1361__4296(.A0 (n_5), .A1 (n_15), .B0 (n_20), .Y (n_21));
  NAND2XL g1362__3772(.A (alu_op[2]), .B (n_18), .Y (n_20));
  AOI21X1 g1363__1474(.A0 (acc_port[0]), .A1 (n_7), .B0 (n_18), .Y
       (n_19));
  NOR3BX1 g1364__4547(.AN (load_acc), .B (immediate_val[1]), .C
       (alu_op[1]), .Y (n_18));
  NOR3BX1 g1365__9682(.AN (load_acc), .B (alu_op[2]), .C (alu_op[1]),
       .Y (n_17));
  OAI21X1 g1366__2683(.A0 (n_1), .A1 (alu_op[1]), .B0 (load_acc), .Y
       (n_16));
  NAND2XL g1367__1309(.A (n_7), .B (alu_op[1]), .Y (n_15));
  NAND3BX1 g1368__6877(.AN (ir_out[11]), .B (ir_out[9]), .C
       (reg_write_en), .Y (n_14));
  MX2X1 g1369__2900(.A (\RF_reg_array[0] [1]), .B (\RF_reg_array[1]
       [1]), .S0 (immediate_val[0]), .Y (n_11));
  MX2X1 g1370__2391(.A (\RF_reg_array[0] [2]), .B (\RF_reg_array[1]
       [2]), .S0 (immediate_val[0]), .Y (n_10));
  MX2X1 g1371__7675(.A (\RF_reg_array[0] [3]), .B (\RF_reg_array[1]
       [3]), .S0 (immediate_val[0]), .Y (n_9));
  NAND2XL g1372__7118(.A (n_8), .B (reg_write_en), .Y (n_13));
  NAND3X1 g1373__8757(.A (ir_out[11]), .B (ir_out[9]), .C
       (reg_write_en), .Y (n_12));
  NOR2XL g1374__1786(.A (ir_out[9]), .B (ir_out[11]), .Y (n_8));
  NOR2XL g1375__5953(.A (immediate_val[1]), .B (alu_op[2]), .Y (n_7));
  INVX1 g1377(.A (acc_port[7]), .Y (n_6));
  INVX1 g1382(.A (acc_port[1]), .Y (n_5));
  CLKINVX1 g1385(.A (acc_port[0]), .Y (n_3));
  INVXL g1386(.A (immediate_val[0]), .Y (n_2));
  INVXL g1387(.A (alu_op[2]), .Y (n_1));
  INVX1 g1392(.A (acc_port[3]), .Y (n_0));
endmodule

